### ISSUE TITLE
issue in frontend web page

### ISSUE THREAD

**Issue by meghakundu** [estivenm0/aventuro#1]
![image](https://github.com/user-attachments/assets/169e08b5-ae5e-44bf-be4f-315ee977d0fe)
Why the frontend webpage is viewed such? Kindly help with this @stivenm0

**Comment by maycolmunoz** [comment]
Generate the JWT secret with php artisan jwt:secret, and if that doesn't work, run php artisan config:clear && php artisan cache:clear && php artisan config:cache.
